# confi serverni sozlaganda  keyin o'chirib tashlasa boladi


#eureka:
#  instance:
#    hostname: localhost
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#server:
#  port: 8070


spring:
  application:
    name: schools
  config:
    import: optional:configserver:http://localhost:8888


#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/schools
#    username: postgres
#    password: axborot1116
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true
#application:
#  config:
#    student-url: http://localhost:8222/api/v1/student
